export const states = [
    { label: "Alabama", value: "AL" },                          { label: "Alaska", value: "AK" },
    { label: "American Samoa", value: "AS" },                   { label: "Arizona", value: "AZ" },
    { label: "Arkansas", value: "AR" },                         { label: "California", value: "CA" },
    { label: "Colorado", value: "CO" },                         { label: "Connecticut", value: "CT" },
    { label: "Delaware", value: "DE" },                         { label: "District Of Columbia", value: "DC" },
    { label: "Federated States Of Micronesia", value: "FM" },   { label: "Florida", value: "FL" },
    { label: "Georgia", value: "GA" },                          { label: "Guam", value: "GU" },
    { label: "Hawaii", value: "HI" },                           { label: "Idaho", value: "ID" },
    { label: "Illinois", value: "IL" },                         { label: "Indiana", value: "IN" },
    { label: "Iowa", value: "IA" },                             { label: "Kansas", value: "KS" },
    { label: "Kentucky", value: "KY" },                         { label: "Louisiana", value: "LA" },
    { label: "Maine", value: "ME" },                            { label: "Marshall Islands", value: "MH" },
    { label: "Maryland", value: "MD" },                         { label: "Massachusetts", value: "MA" },
    { label: "Michigan", value: "MI" },                         { label: "Minnesota", value: "MN" },
    { label: "Mississippi", value: "MS" },                      { label: "Missouri", value: "MO" },
    { label: "Montana", value: "MT" },                          { label: "Nebraska", value: "NE" },
    { label: "Nevada", value: "NV" },                           { label: "New Hampshire", value: "NH" },
    { label: "New Jersey", value: "NJ" },                       { label: "New Mexico", value: "NM" },
    { label: "New York", value: "NY" },                         { label: "North Carolina", value: "NC" },
    { label: "North Dakota", value: "ND" },                     { label: "Northern Mariana Islands", value: "MP" },
    { label: "Ohio", value: "OH" },                             { label: "Oklahoma", value: "OK" },
    { label: "Oregon", value: "OR" },                           { label: "Palau", value: "PW" },
    { label: "Pennsylvania", value: "PA" },                     { label: "Puerto Rico", value: "PR" },
    { label: "Rhode Island", value: "RI" },                     { label: "South Carolina", value: "SC" },
    { label: "South Dakota", value: "SD" },                     { label: "Tennessee", value: "TN" },
    { label: "Texas", value: "TX" },                            { label: "Utah", value: "UT" },
    { label: "Vermont", value: "VT" },                          { label: "Virgin Islands", value: "VI" },
    { label: "Virginia", value: "VA" },                         { label: "Washington", value: "WA" },
    { label: "West Virginia", value: "WV" },                    { label: "Wisconsin", value: "WI" },
    { label: "Wyoming", value: "WY" }
]

export const services = [
    { value: 'Sales', label: 'Sales' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'HumanResources', label: 'Human Resources' },
    { value: 'Legal', label: 'Legal' }
  ]

export const prenoms = ["Adam", "Alex", "Aaron", "Ben", "Carl", "Dan", "David", "Edward", "Fred", "Frank", "George", "Hal", "Hank", "Ike", "John", "Jack", "Joe", "Larry", "Monte", "Matthew", "Mark", "Nathan", "Otto", "Paul", "Peter", "Roger", "Roger", "Steve", "Thomas", "Tim", "Ty", "Victor", "Walter"]
export const noms = ["Anderson", "Ashwoon", "Aikin", "Bateman", "Bongard", "Bowers", "Boyd", "Cannon", "Cast", "Deitz", "Dewalt", "Ebner", "Frick", "Hancock", "Haworth", "Hesch", "Hoffman", "Kassing", "Knutson", "Lawless", "Lawicki", "Mccord", "McCormack", "Miller", "Myers", "Nugent", "Ortiz", "Orwig", "Ory", "Paiser", "Pak", "Pettigrew", "Quinn", "Quizoz", "Ramachandran", "Resnick", "Sagar", "Schickowski", "Schiebel", "Sellon", "Severson", "Shaffer", "Solberg", "Soloman", "Sonderling", "Soukup", "Soulis", "Stahl", "Sweeney", "Tandy", "Trebil", "Trusela", "Trussel", "Turco", "Uddin", "Uflan", "Ulrich", "Upson", "Vader", "Vail", "Valente", "Van Zandt", "Vanderpoel", "Ventotla", "Vogal", "Wagle", "Wagner", "Wakefield", "Weinstein", "Weiss", "Woo", "Yang", "Yates", "Yocum", "Zeaser", "Zeller", "Ziegler", "Bauer", "Baxster", "Casal", "Cataldi", "Caswell", "Celedon", "Chambers", "Chapman", "Christensen", "Darnell", "Davidson", "Davis", "DeLorenzo", "Dinkins", "Doran", "Dugelman", "Dugan", "Duffman", "Eastman", "Ferro", "Ferry", "Fletcher", "Fietzer", "Hylan", "Hydinger", "Illingsworth", "Ingram", "Irwin", "Jagtap", "Jenson", "Johnson", "Johnsen", "Jones", "Jurgenson", "Kalleg", "Kaskel", "Keller", "Leisinger", "LePage", "Lewis", "Linde", "Lulloff", "Maki", "Martin", "McGinnis", "Mills", "Moody", "Moore", "Napier", "Nelson", "Norquist", "Nuttle", "Olson", "Ostrander", "Reamer", "Reardon", "Reyes", "Rice", "Ripka", "Roberts", "Rogers", "Root", "Sandstrom", "Sawyer", "Schlicht", "Schmitt", "Schwager", "Schutz", "Schuster", "Tapia", "Thompson", "Tiernan", "Tisler"]
export const villes = ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana",
"Riverside", "Stockton", "Chula Vista", "Irvine", "Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield", "Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Philadelphia",
"Pittsburgh", "Allentown", "Erie", "Reading",  "Phoenix", "Tucson", "Mesa", "Chandler", "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale"]
export const rues = ["Abby Park Street", "Adelaide Avenue", "Airplane Avenue", "Airport Avenue", "Airport Street", "Andreas Avenue", "Arthur Street",
"Auerbach Avenue", "Auburn Avenue", "Barn Street", "Bay Avenue", "Beatles Avenue", "Belby Road", "Bus Avenue", "California Street",
"Camp Street", "Cavour Avenue", "Central Cesta", "Central Street", "China Avenue", "Communal Square", "Constitution Street", "Copper Street",
"Corn Street", "Costume Street", "Cresson Crescent", "Danish Avenue", "Dean Avenue", "Delaware Avenue", "Delta Street", "Democracy Avenue",
"Department Street", "Dimitri Street", "Dock Street", "Dubnitz Road", "Eastern Cesta", "East Hills Avenue", "Easy Street", "Elgin Avenue",
"Elisabeth Street", "Empire Avenue", "Eppink Square", "Farmer's Lane", "Federation Avenue", "Federation Square", "Flower Avenue",
"Forest Street", "Francis II Street", "Freedom Avenue", "French Street", "Galghard Road", "Gateway Street", "Glider Avenue", "Gold Street",
"Greenpark Avenue", "Hazlett Avenue", "Hendrix Avenue", "Heritage Avenue", "Highway Avenue", "History Avenue", "Hospital Street",
"Hot-air Ballon Avenue", "Hurbadome Avenue", "Hurbanova Street", "Hurricane Avenue", "Ida Street", "Impressionist Avenue", "Industry Street",
"Innovation Avenue", "Jamal Hustróva Street", "Jameson's Crossing", "Katrina Street", "King Arthur I street", "Kings Street", "Law Street",
"Libertas Avenue", "Long Road Avenue", "Lucy Street", "Mandarin Park Lane", "Maple Street", "Marine Avenue", "Mayores Road",
"McCrooke Avenue", "Medieval Street", "Mill Place", "Millstreet", "Mitch Cromwood Avenue", "Monorail Street", "Museum Avenue",
"Newhaven Avenue", "New Orleans Street", "Newport Street", "New Street", "Noble City Path", "Northern Abby Avenue", "Ocean Avenue",
"Oceana Side-street", "Old Port Avenue", "Old Wharf", "Overbanken Road", "Paul Hladovka Avenue", "Pažkoliť Úskalie Avenue", "People's Avenue",
"Pine Avenue", "Pine Street", "Plaza Street", "Poet's Street", "Prachstreet", "Prague Avenue", "Princess Avenue", "Quarry Avenue",
"Queen Mary Elisabeth Alley", "Rail Avenue", "Railway Street", "River Side Road", "River Street", "Rome Avenue", "Sebastian Street",
"School Street", "Shall Street", "Shopping Avenue", "Shopping Street", "Silver Street", "Sobrance Path", "Southern Abby Avenue",
"Southern Avenue", "Southern Millstreet Avenue", "Southern Street", "Square Street", "State Avenue", "Stone Street", "Storm Alley",
"Subway Street", "Swamp Street", "Swit Street", "Sycamore Drive", "Sylvania Avenue", "Technology Avenue", "Temmar Eastwood Avenue",
"Theater Street", "Venice Street", "Vienna Street", "Vlackstreet", "Walden Alley", "Wallstreet", "Water-lily Avenue", "Water Street",
"Western Cesta", "William Street", "Woodstock Street", "Zosnul Street"]